
// actions
export const EQUIPMENT_FETCH_ALL = "EQUIPMENT_FETCH_ALL"
export const EQUIPMENT_FETCH_ONE = "EQUIPMENT_FETCH_ONE"
export const EQUIPMENT_COMMIT_ONE = "EQUIPMENT_COMMIT_ONE"

// setters
export const EQUIPMENT_SET_ALL = "EQUIPMENT_SET_ALL"
export const EQUIPMENT_SET_ONE = "EQUIPMENT_SET_ONE"

// getters
export const EQUIPMENT_GET_ALL = "EQUIPMENT_GET_ALL"
export const EQUIPMENT_GET_ONE = "EQUIPMENT_GET_ONE"