export const PROFILE_CREATE = "PROFILE_CREATE"
export const PROFILE_SET = "PROFILE_SET"

export const SETTINGS_DARK_THEME_SET = "SETTINGS_DARK_THEME_SET"

export const SETTINGS_DARK_THEME_GET = "SETTINGS_DARK_THEME_GET"